<?php
/**
 * Versioned achievement records used by the non-destructive importer.
 *
 * Add one array to `items` for every verified achievement. Increase `version`
 * whenever records are added. A record must have a globally stable `source_id`;
 * the importer uses it to insert the record only once and never updates or
 * restores an existing post.
 *
 * Supported record keys:
 *
 * - source_id (required), title (required), status, slug, date, image.
 * - recipient (string or list), organizer, award, field, level, source_url.
 * - excerpt and content (WordPress-safe HTML).
 * - legacy_recipient, legacy_excerpt, and legacy_content for exact-match,
 *   non-destructive corrections to previously seeded placeholder values.
 *
 * Example source ID: instagram:SHORTCODE:award-slug.
 *
 * @package Queen_Alfalah_Core
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'version'       => '1.2.1',
	'image_version' => '1.0.1',
	'items'         => array(
		array(
			'source_id' => 'instagram:CnUV7LqpRIS:prestasi-kelas-jurusan',
			'title'     => 'Apresiasi Siswa Berprestasi Kelas dan Jurusan 2023',
			'slug'      => 'apresiasi-siswa-berprestasi-kelas-dan-jurusan-2023',
			'status'    => 'publish',
			'date'      => '2023-01-12',
			'image'     => 'apresiasi-kelas-2023.jpg',
			'recipient' => array(
				'Fadila Aulia Zahra — XII OTKP',
				'Siska Rini — XII Asisten Keperawatan',
				'Syarifah Muda’im Dzikrillah — XI Multimedia',
				'Putri Amelia Wakhidah — XI OTKP',
				'Melita Yogi Afriani — XI Asisten Keperawatan',
				'Chessia Nadira Ayuningtyas — X OTKP',
				'Anisa Taufiqatun Nafiah — X Multimedia',
				'Alyanurahma Atantri — X Asisten Keperawatan',
				'Muhammad Hasby Ash-Shiddiqy — X TKJ D',
				'Arjun Rizqi Mubarokh — XI TKJ A',
				'Achmad Durri Zainul Mukhtar — XII TKJ A',
				'Mohammad Syauqi Arrosikh — XII MM C',
			),
			'organizer' => 'SMK Queen Al-Falah',
			'award'     => 'Siswa Berprestasi Kelas dan Jurusan',
			'field'     => 'Akademik',
			'level'     => 'Internal Sekolah',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/CnUV7LqpRIS/',
			'excerpt'   => 'Apresiasi sekolah kepada siswa-siswi yang berprestasi di kelas dan jurusan masing-masing pada awal 2023.',
			'content'   => '<p>SMK Queen Al-Falah memberikan apresiasi kepada siswa-siswi yang menunjukkan capaian terbaik di kelas dan jurusan masing-masing. Penghargaan ini ditujukan sebagai motivasi agar peserta didik terus bertumbuh dan meningkatkan hasil belajarnya.</p><p>Nama para penerima tercantum pada poster resmi sekolah yang diterbitkan dalam unggahan sumber.</p>',
			'legacy_recipient' => 'Siswa-siswi berprestasi di kelas dan jurusan masing-masing (nama tidak dicantumkan pada caption resmi)',
			'legacy_content'   => '<p>SMK Queen Al-Falah memberikan apresiasi kepada siswa-siswi yang menunjukkan capaian terbaik di kelas dan jurusan masing-masing. Penghargaan ini ditujukan sebagai motivasi agar peserta didik terus bertumbuh dan meningkatkan hasil belajarnya.</p><p><strong>Catatan data:</strong> unggahan resmi tidak menuliskan nama penerima pada caption. Daftar penerima dapat dilengkapi oleh pengelola sekolah melalui kolom Penerima apabila dokumen resminya tersedia.</p>',
		),
		array(
			'source_id' => 'instagram:CsnJVpTpxAR:short-movie',
			'title'     => 'Juara 2 Short Movie Festival Komunikasi ke-14',
			'slug'      => 'juara-2-short-movie-festival-komunikasi-14',
			'status'    => 'publish',
			'date'      => '2023-05-20',
			'image'     => 'short-movie-feskom14.webp',
			'recipient' => 'Tim Short Movie SMK Queen Al-Falah (nama anggota tidak dicantumkan pada caption resmi)',
			'organizer' => 'Program Studi Komunikasi dan Penyiaran Islam IAIN Kediri',
			'award'     => 'Juara 2',
			'field'     => 'Film Pendek (Short Movie)',
			'level'     => 'Provinsi Jawa Timur',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/CsnJVpTpxAR/',
			'excerpt'   => 'Tim SMK Queen Al-Falah meraih Juara 2 bidang Short Movie dalam Festival Komunikasi ke-14 IAIN Kediri.',
			'content'   => '<p>Tim Short Movie SMK Queen Al-Falah meraih Juara 2 pada Festival Komunikasi ke-14. Ajang ini menjadi ruang bagi pelajar SMA/SMK sederajat untuk mengembangkan kreativitas, kemampuan bercerita, dan produksi karya audiovisual.</p><p><strong>Catatan data:</strong> nama anggota tim tidak dicantumkan pada caption resmi sehingga halaman ini menggunakan nama tim sekolah.</p>',
		),
		array(
			'source_id' => 'instagram:C0EaEMoJ964:fotografi',
			'title'     => 'Juara 1 Fotografi FESKOM 15',
			'slug'      => 'juara-1-fotografi-feskom-15',
			'status'    => 'publish',
			'date'      => '2023-11-25',
			'image'     => 'fotografi-feskom15.webp',
			'recipient' => 'Ahmad Imam Nabawi — XII Multimedia B',
			'organizer' => 'Program Studi Komunikasi dan Penyiaran Islam, Fakultas Ushuluddin dan Dakwah IAIN Kediri',
			'award'     => 'Juara 1',
			'field'     => 'Fotografi',
			'level'     => 'Eks-Karesidenan Kediri',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/C0EaEMoJ964/',
			'excerpt'   => 'Ahmad Imam Nabawi meraih Juara 1 Lomba Fotografi pada Festival Komunikasi ke-15 IAIN Kediri.',
			'content'   => '<p>Ahmad Imam Nabawi dari kelas XII Multimedia B meraih Juara 1 Lomba Fotografi dalam rangkaian Festival Komunikasi ke-15. Penghargaan diserahkan bertepatan dengan peringatan Hari Guru Nasional.</p>',
		),
		array(
			'source_id' => 'instagram:C2Z0zR6pUky:peringkat-akademik',
			'title'     => 'Peringkat Akademik Siswa 2024',
			'slug'      => 'peringkat-akademik-siswa-2024',
			'status'    => 'publish',
			'date'      => '2024-01-22',
			'image'     => 'peringkat-akademik-2024.webp',
			'recipient' => array(
				'Kelas X — Peringkat 1: Audreylia Mahsa Sheril (LK)',
				'Kelas X — Peringkat 2: Divana Hayatun Nufus (LK)',
				'Kelas X — Peringkat 3: M. Khusen Rohmatullah (TJKT)',
				'Kelas XI — Peringkat 1: M. Nur Wahiddien (MM 2)',
				'Kelas XI — Peringkat 2: Chessia Nadira Ayuningtias (OTKP)',
				'Kelas XI — Peringkat 3: Sifaul Muthoharoh (OTKP)',
				'Kelas XII — Peringkat 1: Muhammad Yazid Irfani (TKJ 1)',
				'Kelas XII — Peringkat 2: Arjun Rizqi Mubarokah (TKJ 1)',
				'Kelas XII — Peringkat 3: Ariq Iqbal (TKJ 2)',
			),
			'organizer' => 'SMK Queen Al-Falah',
			'award'     => 'Peringkat 1–3 setiap jenjang kelas',
			'field'     => 'Akademik',
			'level'     => 'Internal Sekolah',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/C2Z0zR6pUky/',
			'excerpt'   => 'Sembilan siswa kelas X, XI, dan XII memperoleh penghargaan peringkat akademik pada Januari 2024.',
			'content'   => '<p>Penghargaan ini diberikan kepada siswa dengan capaian akademik terbaik pada masing-masing jenjang kelas. Sekolah mengapresiasi ketekunan, kedisiplinan, dan konsistensi belajar para penerima.</p>',
		),
		array(
			'source_id' => 'instagram:C-sWJRpzQO1:lbb-putra',
			'title'     => 'Juara 2 Lomba Baris Berbaris Putra Kecamatan Mojo',
			'slug'      => 'juara-2-lomba-baris-berbaris-putra-kecamatan-mojo',
			'status'    => 'publish',
			'date'      => '2024-08-06',
			'image'     => 'lbb-putra-kecamatan-mojo-2024.jpg',
			'recipient' => 'Tim Baris Berbaris Putra SMK Queen Al-Falah',
			'organizer' => 'Panitia Lomba Baris Berbaris Kecamatan Mojo',
			'award'     => 'Juara 2',
			'field'     => 'Baris Berbaris',
			'level'     => 'Kecamatan Mojo',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/C-sWJRpzQO1/',
			'excerpt'   => 'Tim putra SMK Queen Al-Falah meraih Juara 2 Lomba Baris Berbaris tingkat Kecamatan Mojo.',
			'content'   => '<p>Tim putra SMK Queen Al-Falah meraih Juara 2 dalam Lomba Baris Berbaris tingkat Kecamatan Mojo. Capaian ini merupakan hasil latihan disiplin, kekompakan, dan kerja sama seluruh anggota tim.</p>',
		),
		array(
			'source_id' => 'instagram:C-sWJRpzQO1:lbb-putri',
			'title'     => 'Juara 3 Lomba Baris Berbaris Putri Kecamatan Mojo',
			'slug'      => 'juara-3-lomba-baris-berbaris-putri-kecamatan-mojo',
			'status'    => 'publish',
			'date'      => '2024-08-06',
			'legacy_image' => 'lbb-putri-kecamatan-mojo-2024.jpg',
			'recipient' => 'Tim Baris Berbaris Putri SMK Queen Al-Falah',
			'organizer' => 'Panitia Lomba Baris Berbaris Kecamatan Mojo',
			'award'     => 'Juara 3',
			'field'     => 'Baris Berbaris',
			'level'     => 'Kecamatan Mojo',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/C-sWJRpzQO1/',
			'excerpt'   => 'Tim putri SMK Queen Al-Falah meraih Juara 3 Lomba Baris Berbaris tingkat Kecamatan Mojo.',
			'content'   => '<p>Tim putri SMK Queen Al-Falah meraih Juara 3 dalam Lomba Baris Berbaris tingkat Kecamatan Mojo. Prestasi ini menunjukkan semangat juang, disiplin, dan kekompakan para peserta.</p><p><strong>Catatan dokumentasi:</strong> unggahan sumber menyebut capaian regu putri pada caption, tetapi foto yang tersedia menampilkan regu putra. Gambar unggulan sengaja belum ditetapkan agar tidak terjadi salah atribusi; pengelola sekolah dapat memasang foto regu putri yang benar melalui Media Library.</p>',
		),
		array(
			'source_id' => 'instagram:DE4ySByJl8x:peringkat-paralel',
			'title'     => 'Penghargaan Peringkat Paralel Siswa 2024/2025',
			'slug'      => 'penghargaan-peringkat-paralel-siswa-2024-2025',
			'status'    => 'publish',
			'date'      => '2025-01-16',
			'image'     => 'peringkat-paralel-2024-2025.jpg',
			'recipient' => 'Siswa-siswi peraih peringkat paralel SMK Queen Al-Falah (nama tidak dicantumkan pada caption resmi)',
			'organizer' => 'SMK Queen Al-Falah',
			'award'     => 'Peringkat Paralel',
			'field'     => 'Akademik',
			'level'     => 'Internal Sekolah',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DE4ySByJl8x/',
			'excerpt'   => 'Penghargaan bagi siswa peraih peringkat paralel tahun ajaran 2024/2025.',
			'content'   => '<p>SMK Queen Al-Falah memberikan penghargaan kepada siswa-siswi peraih peringkat paralel tahun ajaran 2024/2025. Apresiasi ini menjadi pengakuan atas semangat belajar, ketekunan, dan kerja keras para peserta didik.</p><p><strong>Catatan data:</strong> nama penerima tidak dituliskan pada caption resmi dan dapat dilengkapi oleh pengelola sekolah setelah daftar resminya tersedia.</p>',
		),
		array(
			'source_id' => 'instagram:DJ5bZqXTYoe:video-lawatan-sejarah',
			'title'     => 'Juara 2 Video Lawatan Sejarah 2025',
			'slug'      => 'juara-2-video-lawatan-sejarah-2025',
			'status'    => 'publish',
			'date'      => '2025-05-21',
			'image'     => 'video-lawatan-sejarah-2025.jpg',
			'recipient' => 'Ahmada Zidni Mubarok — XI DKV 4',
			'organizer' => 'Dinas Pariwisata dan Kebudayaan Kabupaten Kediri',
			'award'     => 'Juara 2',
			'field'     => 'Video Sejarah',
			'level'     => 'Kabupaten Kediri',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DJ5bZqXTYoe/',
			'excerpt'   => 'Ahmada Zidni Mubarok meraih Juara 2 Lomba Video Lawatan Sejarah 2025.',
			'content'   => '<p>Ahmada Zidni Mubarok dari kelas XI DKV 4 meraih Juara 2 Lomba Video Lawatan Sejarah. Karya tersebut memadukan visual storytelling dengan pesan sejarah untuk mengenalkan kembali warisan lokal melalui media digital.</p>',
		),
		array(
			'source_id' => 'instagram:DL37-OhpfR2:video-edukatif',
			'title'     => 'Juara 2 Video Edukatif Pekan Pancasila 2025',
			'slug'      => 'juara-2-video-edukatif-pekan-pancasila-2025',
			'status'    => 'publish',
			'date'      => '2025-07-09',
			'image'     => 'video-edukatif-pancasila-2025.webp',
			'recipient' => array(
				'Rafikal Ramadhani — XI DKV 4 (Produser)',
				'Agastya Atthariz Maulana — XI TJKT 1 (Penulis)',
			),
			'organizer' => 'HMPS PPKn Universitas Muhammadiyah Purwokerto',
			'award'     => 'Juara 2',
			'field'     => 'Video Edukatif Pancasila',
			'level'     => 'Nasional',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DL37-OhpfR2/',
			'excerpt'   => 'Rafikal Ramadhani dan Agastya Atthariz Maulana meraih Juara 2 Video Edukatif dalam Pekan Pancasila 2025.',
			'content'   => '<p>Karya video edukatif SMK Queen Al-Falah meraih Juara 2 dalam Pekan Pancasila 2025. Poster resmi mencantumkan Rafikal Ramadhani sebagai produser dan Agastya Atthariz Maulana sebagai penulis, dengan pendamping Zalza Meira Cahyani, S.H.</p><p>Video tersebut menjadi media kreatif untuk menyampaikan semangat cinta tanah air dan penerapan nilai-nilai Pancasila.</p>',
			'legacy_recipient' => 'Tim Video Edukatif SMK Queen Al-Falah (nama anggota tidak dicantumkan pada caption resmi)',
			'legacy_excerpt'   => 'Tim SMK Queen Al-Falah meraih Juara 2 Video Edukatif dalam Pekan Pancasila 2025.',
			'legacy_content'   => '<p>Karya video edukatif siswa SMK Queen Al-Falah meraih Juara 2 dalam Pekan Pancasila 2025. Video tersebut menjadi media kreatif untuk menyampaikan semangat cinta tanah air dan penerapan nilai-nilai Pancasila.</p><p><strong>Catatan data:</strong> nama anggota tim tidak dicantumkan pada caption resmi sehingga penerima ditulis sebagai tim sekolah.</p>',
		),
		array(
			'source_id' => 'instagram:DNAZwbsv_-P:peringkat-paralel',
			'title'     => 'Apresiasi Peringkat Paralel Terbaik 2025/2026',
			'slug'      => 'apresiasi-peringkat-paralel-terbaik-2025-2026',
			'status'    => 'publish',
			'date'      => '2025-08-06',
			'image'     => 'peringkat-paralel-2025-2026.jpg',
			'recipient' => array(
				'Achmad Muchlas — X TJKT 1',
				'Thalita Zakia Ahmad — X DKV 1',
				'Alica Ramadhani — X MPLB',
				'Rizky Pratama — XI TJKT 1',
				'Divana Hayatun Nufus — XI LK',
				'Villa — XI DKV 1',
			),
			'organizer' => 'SMK Queen Al-Falah',
			'award'     => 'Peringkat Paralel Terbaik',
			'field'     => 'Akademik',
			'level'     => 'Internal Sekolah',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DNAZwbsv_-P/',
			'excerpt'   => 'Enam siswa kelas X dan XI menerima apresiasi peringkat paralel terbaik pada awal tahun ajaran 2025/2026.',
			'content'   => '<p>Pada rangkaian kegiatan awal tahun ajaran 2025/2026, sekolah memberikan apresiasi kepada enam siswa peraih peringkat paralel terbaik. Penghargaan ini menegaskan pentingnya ketekunan dan konsistensi dalam belajar.</p><p>Nama para penerima tercantum pada poster resmi sekolah yang diterbitkan dalam unggahan sumber.</p>',
			'legacy_recipient' => 'Siswa-siswi peraih peringkat paralel terbaik (nama tidak dicantumkan pada caption resmi)',
			'legacy_excerpt'   => 'Apresiasi bagi siswa peraih peringkat paralel terbaik pada awal tahun ajaran 2025/2026.',
			'legacy_content'   => '<p>Pada rangkaian kegiatan awal tahun ajaran 2025/2026, sekolah memberikan apresiasi kepada siswa-siswi peraih peringkat paralel terbaik. Penghargaan ini menegaskan pentingnya ketekunan dan konsistensi dalam belajar.</p><p><strong>Catatan data:</strong> caption resmi tidak memuat nama penerima. Pengelola dapat melengkapinya melalui kolom Penerima setelah daftar resmi tersedia.</p>',
		),
		array(
			'source_id' => 'instagram:DQPEpHHCTTb:juara-harapan-1',
			'title'     => 'Juara Harapan 1 LKTI Muamalah Fair 2025',
			'slug'      => 'juara-harapan-1-lkti-muamalah-fair-2025',
			'status'    => 'publish',
			'date'      => '2025-10-01',
			'image'     => 'lkti-muamalah-harapan-1-2025.webp',
			'recipient' => array(
				'Agastya Atthariz Maulana — XII TJKT 1',
				'Muhammad Khusen Rohmatullah — XII TJKT 1',
				'Ahmad Tegar Kuncoro — XII TJKT 2',
			),
			'legacy_recipient' => array(
				'Agastya Atthariz Maulana — XII TJKT 1',
				'Muhammad Khusen Rohmatullah — XII TJKT 1',
				'Ahmad Tegar Kuncoro — XI TJKT 2',
			),
			'organizer' => 'HMPS Hukum Ekonomi Syariah, Fakultas Syariah UIN Sayyid Ali Rahmatullah Tulungagung',
			'award'     => 'Juara Harapan 1',
			'field'     => 'Lomba Karya Tulis Ilmiah',
			'level'     => 'Provinsi Jawa Timur',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DQPEpHHCTTb/',
			'excerpt'   => 'Tim TJKT meraih Juara Harapan 1 dalam LKTI Muamalah Fair 2025 tingkat Provinsi Jawa Timur.',
			'content'   => '<p>Agastya Atthariz Maulana, Muhammad Khusen Rohmatullah, dan Ahmad Tegar Kuncoro meraih Juara Harapan 1 dalam Lomba Karya Tulis Ilmiah Muamalah Fair 2025.</p><p>Tim dibimbing oleh Zalza Meira Cahyani, S.H., Guru PPKn SMK Queen Al-Falah.</p>',
		),
		array(
			'source_id' => 'instagram:DQPEpHHCTTb:juara-3',
			'title'     => 'Juara 3 LKTI Muamalah Fair 2025',
			'slug'      => 'juara-3-lkti-muamalah-fair-2025',
			'status'    => 'publish',
			'date'      => '2025-10-01',
			'image'     => 'lkti-muamalah-juara-3-2025.webp',
			'recipient' => array(
				'Zahra Faiqotun Nashir — XII MPLB',
				'Alica Ramadhani — XI MPLB',
				'Wardatul Aulia Hidayatullah — XII DKV 1',
			),
			'organizer' => 'HMPS Hukum Ekonomi Syariah, Fakultas Syariah UIN Sayyid Ali Rahmatullah Tulungagung',
			'award'     => 'Juara 3',
			'field'     => 'Lomba Karya Tulis Ilmiah',
			'level'     => 'Provinsi Jawa Timur',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DQPEpHHCTTb/',
			'excerpt'   => 'Tim lintas program keahlian meraih Juara 3 dalam LKTI Muamalah Fair 2025 tingkat Provinsi Jawa Timur.',
			'content'   => '<p>Zahra Faiqotun Nashir, Alica Ramadhani, dan Wardatul Aulia Hidayatullah meraih Juara 3 dalam Lomba Karya Tulis Ilmiah Muamalah Fair 2025.</p><p>Tim dibimbing oleh Zalza Meira Cahyani, S.H., Guru PPKn SMK Queen Al-Falah.</p>',
		),
		array(
			'source_id' => 'instagram:DQjhO8PiUO5:sneakers-hand-painting',
			'title'     => 'Juara 1 Sneakers Hand Painting School Contest XVII',
			'slug'      => 'juara-1-sneakers-hand-painting-school-contest-17',
			'status'    => 'publish',
			'date'      => '2025-10-26',
			'image'     => 'sneakers-hand-painting-2025.jpg',
			'recipient' => 'Muhammad Fahmi Ibrahim — X DKV 4',
			'organizer' => 'Jawa Pos Radar Kediri',
			'award'     => 'Juara 1',
			'field'     => 'Sneakers Hand Painting',
			'level'     => 'Kediri Raya',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DQjhO8PiUO5/',
			'excerpt'   => 'Muhammad Fahmi Ibrahim meraih Juara 1 Sneakers Hand Painting pada School Contest XVII 2025.',
			'content'   => '<p>Muhammad Fahmi Ibrahim dari kelas X DKV 4 meraih Juara 1 Sneakers Hand Painting Competition dalam School Contest XVII GenZverse 2025: LiterAction.</p><p>Persiapan dan pendampingan dilakukan bersama Pradita Ratna Arianti, S.Pd.</p>',
		),
		array(
			'source_id' => 'instagram:DVBm49GiYcL:tka-bahasa-arab',
			'title'     => 'Nilai Terbaik TKA Bahasa Arab Jenjang SMK 2025',
			'slug'      => 'nilai-terbaik-tka-bahasa-arab-jenjang-smk-2025',
			'status'    => 'publish',
			'date'      => '2026-02-21',
			'image'     => 'tka-bahasa-arab-2025.webp',
			'recipient' => 'Wardatul Aulia Hidayatullah — XII DKV 1',
			'organizer' => 'Direktorat Sekolah Menengah Kejuruan, Kementerian Pendidikan Dasar dan Menengah',
			'award'     => 'Peraih Nilai Terbaik',
			'field'     => 'TKA Bahasa Arab',
			'level'     => 'Nasional — Jenjang SMK',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DVBm49GiYcL/',
			'excerpt'   => 'Wardatul Aulia Hidayatullah memperoleh penghargaan nilai terbaik TKA Bahasa Arab jenjang SMK 2025.',
			'content'   => '<p>Wardatul Aulia Hidayatullah dari kelas XII DKV 1 memperoleh penghargaan sebagai peraih nilai terbaik Tes Kemampuan Akademik mata pelajaran Bahasa Arab jenjang SMK tahun 2025.</p>',
		),
		array(
			'source_id' => 'instagram:DVBm49GiYcL:lks-bilingual-secretary',
			'title'     => 'Juara 1 LKS Bilingual Secretary Kabupaten Kediri 2026',
			'slug'      => 'juara-1-lks-bilingual-secretary-kabupaten-kediri-2026',
			'status'    => 'publish',
			'date'      => '2026-02-21',
			'image'     => 'lks-bilingual-secretary-2026.webp',
			'recipient' => 'Zahra Faiqotun Nashir — XII MPLB',
			'organizer' => 'Dinas Pendidikan Provinsi Jawa Timur, Cabang Dinas Pendidikan Wilayah Kediri',
			'award'     => 'Juara 1 Kabupaten; Delegasi Provinsi',
			'field'     => 'LKS Bilingual Secretary',
			'level'     => 'Kabupaten Kediri; Delegasi Provinsi Jawa Timur',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DVBm49GiYcL/',
			'excerpt'   => 'Zahra Faiqotun Nashir meraih Juara 1 LKS Bilingual Secretary Kabupaten Kediri dan menjadi delegasi tingkat provinsi.',
			'content'   => '<p>Zahra Faiqotun Nashir dari kelas XII MPLB meraih Juara 1 bidang Bilingual Secretary pada LKS Dikmen Kabupaten Kediri 2026. Hasil tersebut mengantarkannya menjadi delegasi ke tingkat Provinsi Jawa Timur.</p><p>Pembimbing: Ariska Fisma Lestari, S.Pd.</p>',
		),
		array(
			'source_id' => 'instagram:DVBm49GiYcL:lks-health-social-care',
			'title'     => 'Juara 2 LKS Health and Social Care Kabupaten Kediri 2026',
			'slug'      => 'juara-2-lks-health-social-care-kabupaten-kediri-2026',
			'status'    => 'publish',
			'date'      => '2026-02-21',
			'image'     => 'lks-health-social-care-2026.webp',
			'recipient' => 'Atina Nafisatal Hidayah — XII Layanan Kesehatan',
			'organizer' => 'Dinas Pendidikan Provinsi Jawa Timur, Cabang Dinas Pendidikan Wilayah Kediri',
			'award'     => 'Juara 2 Kabupaten; Delegasi Provinsi',
			'field'     => 'LKS Health and Social Care',
			'level'     => 'Kabupaten Kediri; Delegasi Provinsi Jawa Timur',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DVBm49GiYcL/',
			'excerpt'   => 'Atina Nafisatal Hidayah meraih Juara 2 LKS Health and Social Care Kabupaten Kediri dan menjadi delegasi tingkat provinsi.',
			'content'   => '<p>Atina Nafisatal Hidayah dari kelas XII Layanan Kesehatan meraih Juara 2 bidang Health and Social Care pada LKS Dikmen Kabupaten Kediri 2026. Capaian tersebut mengantarkannya menjadi delegasi ke tingkat Provinsi Jawa Timur.</p><p>Pembimbing: Siti Khamidatul Mahbubah, S.Kep., Ns.</p>',
		),
		array(
			'source_id' => 'instagram:DXnc-npCTrf:ecofest-manajemen-bisnis-syariah',
			'title'     => 'Juara 3 ECOFEST 2026 Bidang Manajemen Bisnis Syariah',
			'slug'      => 'juara-3-ecofest-2026-manajemen-bisnis-syariah',
			'status'    => 'publish',
			'date'      => '2026-04-17',
			'image'     => 'ecofest-2026.webp',
			'recipient' => 'Tim Nova Fortune Al Baraka — SMK Queen Al-Falah',
			'organizer' => 'Fakultas Ekonomi dan Bisnis Islam UIN Sayyid Ali Rahmatullah Tulungagung',
			'award'     => 'Juara 3',
			'field'     => 'Manajemen Bisnis Syariah — The Next CEO & Start-up',
			'level'     => 'Nasional',
			'source_url' => 'https://www.instagram.com/smkqueenalfalah_official/p/DXnc-npCTrf/',
			'excerpt'   => 'Tim Nova Fortune Al Baraka meraih Juara 3 ECOFEST 2026 pada bidang Manajemen Bisnis Syariah.',
			'content'   => '<p>Tim Nova Fortune Al Baraka dari SMK Queen Al-Falah meraih Juara 3 ECOFEST 2026 pada kategori Manajemen Bisnis Syariah: The Next CEO &amp; Start-up. Final nasional diikuti pelajar SMA/MA/SMK dari berbagai daerah di Indonesia.</p><p><strong>Catatan data:</strong> unggahan resmi mencantumkan nama tim, tetapi tidak menuliskan nama seluruh anggotanya.</p>',
		),
	),
);
